spring:
  datasource:
    url: jdbc:mysql://localhost:13306/msc_dev
    username: msc_dev_user
    password: passwd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

## Once generate the script, comment it out.
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: musca_database_create.sql